server:
  port: 9090
wx:
  cp:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ????
spring:
  mvc:
    path match:
      # ????
      matching-strategy: ant-path-matcher
  application:
    name: watch-service
  profiles:
    active: dev