spring:
  datasource:
    url: jdbc:mysql://localhost:3306/watchs?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual # 手动应答
        prefetch: 1 #每次从队列中取一个,轮询分发，默认是公平分发
        retry:
          max-attempts: 5 # 重试次数
          enabled: true # 开启重试
static-file-location:
  #本地地址
  upload-url: "/Users/yeninghui/Desktop/testUploadFile/"